import Head from "next/head";
import Link from "next/link";
import { SiteHeader } from "../components/site-header";
import { SiteFooter } from "../components/site-footer";
import { Container } from "../components/container";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Head>
        <title>Terms of Service — Visum</title>
        <meta
          name="description"
          content="Visum's terms of service govern the use of our AI agent readiness scanning platform. Review our terms before using the service."
        />
        <link rel="canonical" href="https://visum-eight.vercel.app/terms" />
        <meta property="og:title" content="Terms of Service — Visum" />
        <meta
          property="og:description"
          content="Visum's terms of service govern the use of our AI agent readiness scanning platform."
        />
        <meta name="twitter:title" content="Terms of Service — Visum" />
        <meta
          name="twitter:description"
          content="Visum's terms of service govern the use of our AI agent readiness scanning platform."
        />
        <meta name="robots" content="index, follow" />
      </Head>

      <SiteHeader />

      <main className="flex-1">
        <section className="py-24">
          <Container>
            <div className="mx-auto max-w-3xl">
              <div className="inline-flex self-start rounded-full bg-accent/10 px-3 py-1 text-xs text-accent mb-4">
                Legal
              </div>
              <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground mb-2">
                Terms of Service
              </h1>
              <p className="text-sm text-muted-foreground mb-8">
                Last updated: July 1, 2026
              </p>

              <div className="prose prose-invert max-w-none space-y-8 text-sm leading-relaxed text-muted-foreground">
                {/* Acceptance */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Acceptance of Terms</h2>
                  <p>
                    By accessing or using Visum (&ldquo;the Service&rdquo;), you agree to be bound by these
                    Terms of Service. If you do not agree to these terms, please do not use the Service.
                  </p>
                </section>

                {/* Description */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Description of Service</h2>
                  <p>
                    Visum provides an AI agent readiness scanning tool that evaluates how well websites are
                    optimized for discovery and use by AI systems, including ChatGPT, Claude, Perplexity, and
                    AI-powered search engines. The Service scans publicly available URLs and generates reports
                    based on automated checks.
                  </p>
                </section>

                {/* Acceptable Use */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Acceptable Use</h2>
                  <p>You agree to use the Service only for lawful purposes and in accordance with these terms. You agree not to:</p>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>Use the Service to scan websites you do not own or have explicit permission to scan</li>
                    <li>Submit URLs that contain illegal, harmful, or malicious content</li>
                    <li>Attempt to circumvent rate limits, security measures, or access restrictions</li>
                    <li>Use the Service for competitive intelligence gathering against other scanning services</li>
                    <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
                    <li>Use the Service in any way that could damage, disable, or impair our infrastructure</li>
                    <li>Submit false or misleading information, including fake email addresses</li>
                  </ul>
                </section>

                {/* Intellectual Property */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Intellectual Property</h2>
                  <p>
                    The Service, including its design, code, algorithms, branding, and content, is owned by
                    Visum and protected by applicable intellectual property laws. You may not reproduce,
                    distribute, modify, or create derivative works without our express written permission.
                  </p>
                  <p className="mt-2">
                    Scan reports generated by the Service are provided for your internal use. You may share
                    your report results, but you may not redistribute the Service itself.
                  </p>
                </section>

                {/* Disclaimer */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Disclaimer of Warranties</h2>
                  <p>
                    THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; WITHOUT
                    WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. VISUM SPECIFICALLY DISCLAIMS ALL WARRANTIES,
                    INCLUDING BUT NOT LIMITED TO:
                  </p>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>That the Service will meet your specific requirements or expectations</li>
                    <li>That the Service will be uninterrupted, timely, secure, or error-free</li>
                    <li>That scan results are complete, accurate, or reliable</li>
                    <li>That fixing issues identified by scans will result in improved AI visibility</li>
                    <li>That the Service will achieve any particular outcome for your website</li>
                  </ul>
                  <p className="mt-3">
                    Scan results are automated assessments and should not be the sole basis for business
                    decisions. We recommend consulting with qualified professionals for critical SEO and
                    technical decisions.
                  </p>
                </section>

                {/* Limitation of Liability */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Limitation of Liability</h2>
                  <p>
                    TO THE FULLEST EXTENT PERMITTED BY LAW, VISUM SHALL NOT BE LIABLE FOR ANY INDIRECT,
                    INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
                  </p>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>Loss of profits, data, or business opportunity</li>
                    <li>Costs of procurement of substitute services</li>
                    <li>Business interruption</li>
                    <li>Damages arising from reliance on scan results</li>
                    <li>Damages resulting from use or inability to use the Service</li>
                  </ul>
                  <p className="mt-3">
                    Our total liability to you shall not exceed the amount paid by you (if any) for access to
                    the Service in the twelve months preceding the claim.
                  </p>
                </section>

                {/* Third-Party Links */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Third-Party Links and Services</h2>
                  <p>
                    The Service may contain links to third-party websites or services. Visum is not responsible
                    for the content, privacy practices, or terms of third-party sites. Your use of third-party
                    services is at your own risk.
                  </p>
                </section>

                {/* Termination */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Termination</h2>
                  <p>
                    We reserve the right to suspend or terminate your access to the Service at any time,
                    without notice, for any violation of these terms or for any conduct that we deem
                    harmful to the Service or other users.
                  </p>
                </section>

                {/* Changes */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Changes to the Terms</h2>
                  <p>
                    We may modify these Terms of Service at any time. Changes will be effective immediately
                    upon posting. Your continued use of the Service after changes constitutes acceptance of
                    the modified terms. We will update the &ldquo;Last updated&rdquo; date at the top of this
                    page.
                  </p>
                </section>

                {/* Governing Law */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Governing Law</h2>
                  <p>
                    These terms shall be governed by and construed in accordance with the laws of India,
                    without regard to its conflict of law provisions. Any disputes arising from these terms
                    shall be resolved in the courts of India.
                  </p>
                </section>

                {/* Severability */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Severability</h2>
                  <p>
                    If any provision of these terms is held to be unenforceable or invalid, the remaining
                    provisions shall continue in full force and effect.
                  </p>
                </section>

                {/* Contact */}
                <section>
                  <h2 className="text-xl font-semibold text-foreground mb-3">Contact</h2>
                  <p>
                    For questions about these terms, please contact us at{" "}
                    <a href="mailto:utsavkumar1283@gmail.com" className="text-accent hover:text-accent/80 underline underline-offset-2">
                      utsavkumar1283@gmail.com
                    </a>{" "}
                    or visit our{" "}
                    <Link href="/contact" className="text-accent hover:text-accent/80 underline underline-offset-2">
                      Contact page
                    </Link>.
                  </p>
                </section>
              </div>
            </div>
          </Container>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
