/**
 * Register a domain for AI-crawler tracking, and read back its ingest key.
 *
 * The key is generated by the database and only ever returned to the account
 * that owns the site, so it is never guessable from the domain.
 */
import { getAuthedUser } from "../../../lib/supabase/auth";
import { getSupabaseAdminClient } from "../../../lib/supabase/admin";
import { resolveBilling } from "../../../lib/server/account";

const MAX_SITES = 10;

/**
 * Reduce anything a person might paste — a full URL, a www host, trailing
 * slash, mixed case — to the bare hostname the collector will report.
 */
export function normaliseHost(input) {
  if (typeof input !== "string") return "";
  let value = input.trim().toLowerCase();
  if (!value) return "";
  if (!/^https?:\/\//.test(value)) value = `https://${value}`;
  try {
    const { hostname } = new URL(value);
    return hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

export default async function handler(req, res) {
  const user = await getAuthedUser({ req, res });
  if (!user) {
    return res.status(401).json({ error: "Sign in first.", code: "unauthenticated" });
  }

  const admin = getSupabaseAdminClient();
  if (!admin) {
    return res.status(503).json({ error: "Temporarily unavailable." });
  }

  if (req.method === "GET") {
    const { data, error } = await admin
      .from("tracked_sites")
      .select("id, domain, ingest_key, created_at")
      .eq("user_id", user.id)
      .order("created_at", { ascending: true });

    if (error) {
      console.error("[api/analytics/sites] read failed:", error.message);
      return res.status(503).json({ error: "Could not load your sites." });
    }
    return res.status(200).json({ sites: data || [] });
  }

  if (req.method === "POST") {
    const domain = normaliseHost(req.body?.domain);
    if (!domain || !domain.includes(".")) {
      return res.status(400).json({ error: "Enter a valid domain, like example.com." });
    }

    const { count, error: countError } = await admin
      .from("tracked_sites")
      .select("id", { count: "exact", head: true })
      .eq("user_id", user.id);
    if (countError) {
      console.error("[api/analytics/sites] count failed:", countError.message);
      return res.status(503).json({ error: "Could not add that site." });
    }
    if ((count ?? 0) >= MAX_SITES) {
      return res
        .status(400)
        .json({ error: `You can track up to ${MAX_SITES} sites. Remove one to add another.` });
    }

    const { orgId } = await resolveBilling(admin, user.id);

    const { data, error } = await admin
      .from("tracked_sites")
      .insert({ user_id: user.id, org_id: orgId, domain })
      .select("id, domain, ingest_key, created_at")
      .single();

    if (error) {
      // The (user_id, domain) unique constraint — already tracked.
      if (error.code === "23505") {
        return res.status(409).json({ error: "You're already tracking that domain." });
      }
      console.error("[api/analytics/sites] insert failed:", error.message);
      return res.status(503).json({ error: "Could not add that site." });
    }

    return res.status(201).json({ site: data });
  }

  if (req.method === "DELETE") {
    const id = req.body?.id;
    if (!id) return res.status(400).json({ error: "Which site?" });

    // Scoped to the caller, so an id from another account deletes nothing.
    const { error } = await admin
      .from("tracked_sites")
      .delete()
      .eq("id", id)
      .eq("user_id", user.id);

    if (error) {
      console.error("[api/analytics/sites] delete failed:", error.message);
      return res.status(503).json({ error: "Could not remove that site." });
    }
    return res.status(200).json({ ok: true });
  }

  res.setHeader("Allow", "GET, POST, DELETE");
  return res.status(405).json({ error: "Method not allowed" });
}
